import type { Metadata } from "next";
import { DM_Mono, Fraunces, Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";

const dmMono = DM_Mono({ subsets: ["latin"], variable: "--font-mono", weight: ["300", "400", "500"] });

const fraunces = Fraunces({ subsets: ["latin"], variable: "--font-fraunces" });

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={cn("h-full", "antialiased", geistSans.variable, geistMono.variable, "font-mono", dmMono.variable, fraunces.variable)}
    >
      <body 
        className="min-h-full flex flex-col bg-amber-50 align-middle content-start justify-items-center">
        {children}
      </body>
    </html>
  );
}
